admin_app/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.views.generic.base import TemplateView
from .views import *

app_name = 'admin_app'

urlpatterns = [
    re_path(r'^accounts/', include("django.contrib.auth.urls")),
    re_path(r'^$',  ClothingProductList.as_view(), name='index'),
    # Collections
    re_path(r'^collections/create/$', ClothingCollectionCreate.as_view(), name='collection-create'),
    re_path('collections/$', ClothingCollectionList.as_view(), name='collection-list'),
    re_path('collections/(?P<pk>[^/]*)/delete/$', ClothingCollectionDelete.as_view(), name='collection-delete'),
    re_path(r'^collections/(?P<pk>[^/]*)/update/$', ClothingCollectionUpdate.as_view(), name='collection-update'),
    # Categories
    re_path(r'^categories/create/$', CategoryCreate.as_view(), name='category-create'),
    re_path('categories/$', CategoryList.as_view(), name='category-list'),
    re_path('categories/(?P<pk>[^/]*)/delete/$', CategoryDelete.as_view(), name='category-delete'),
    re_path(r'^categories/(?P<pk>[^/]*)/update/$', CategoryUpdate.as_view(), name='category-update'),
    # Global Config
    re_path(r'^global-configs/create/$', GlobalConfigCreate.as_view(), name='global-config-create'),
    re_path('global-configs/$', GlobalConfigList.as_view(), name='global-config-list'),
    re_path(r'^global-configs/(?P<pk>[^/]*)/update/$', GlobalConfigUpdate.as_view(), name='global-config-update'),
    re_path(r'^global-configs/(?P<pk>[^/]*)/delete/$', GlobalConfigDelete.as_view(), name='global-config-delete'),
    # Custom Color
    re_path(r'^custom-colors/create/$', CustomColorCreate.as_view(), name='custom-color-create'),
    re_path('custom-colors/$', CustomColorList.as_view(), name='custom-color-list'),
    re_path(r'^custom-colors/(?P<pk>[^/]*)/update/$', CustomColorUpdate.as_view(), name='custom-color-update'),
    re_path(r'^custom-colors/(?P<pk>[^/]*)/delete/$', CustomColorDelete.as_view(), name='custom-color-delete'),
    # Clothing Product
    re_path(r'^clothing-products/create/$', ClothingProductCreate.as_view(), name='clothing-product-create'),
    re_path('clothing-products/$', ClothingProductList.as_view(), name='clothing-product-list'),
    re_path(r'^clothing-products/(?P<pk>[^/]*)/update/$', ClothingProductUpdate.as_view(),
            name='clothing-product-update'),
    re_path(r'^clothing-products/(?P<pk>[^/]*)/delete/$', ClothingProductDelete.as_view(),
            name='clothing-product-delete'),
    re_path(r'^collections/(?P<pk>[^/]*)/clothing-products/$', ClothingProductFilterCollection.as_view(),
            name='clothing-products-collection-filter'),
    re_path(r'^categories/(?P<pk>[^/]*)/clothing-products/$', ClothingProductFilterCategory.as_view(),
            name='clothing-products-category-filter'),
    # Orders
    re_path('orders/$', OrderList.as_view(), name='order-list'),
    re_path(r'^orders/create/$', OrderCreate.as_view(), name='order-create'),
    re_path(r'^orders/(?P<pk>[^/]*)/update/$', OrderUpdate.as_view(), name='order-update'),
    re_path(r'^orders/(?P<pk>[^/]*)/delete/$', OrderDelete.as_view(), name='order-delete'),
    re_path(r'^orders/(?P<pk>[^/]*)/datail/$', OrderDetail.as_view(), name='order-detail'),
    #Payment
    re_path(r'^payments/create/$', PaymentCreate.as_view(), name='payment-create'),
    re_path('payments/$', PaymentList.as_view(), name='payment-list'),
    re_path('categpaymentsories/(?P<pk>[^/]*)/delete/$', PaymentDelete.as_view(), name='payment-delete'),
    re_path(r'^payments/(?P<pk>[^/]*)/update/$', PaymentUpdate.as_view(), name='payment-update'),
]

store_app/urls.py
from django.urls import re_path
from .views import *

app_name = 'store_app'

urlpatterns = [
    re_path('clothing-products/(?P<page>[^/]*)/$', ClothingProductListAPIView.as_view(),
            name='clothing-products-api-list'),
    re_path('clothing-products/items/(?P<id>[0-9]+)/$', ClothingProductDetailAPIView.as_view(),
            name='clothing-products-api-detail'),
    re_path('clothing-collections/$', ClothingCollectionListAPIView.as_view(),
            name='clothing-collections-api-list'),
    re_path('clothing-collections/filter/names/$', ClothingCollectionsByNameYearListAPIView.as_view(),
            name='clothing-collections-filter-name-api-list'),
    re_path('clothing-collections/(?P<id>[0-9]+)/$', ClothingCollectionDetailAPIView.as_view(),
            name='clothing-collections-api-detail'),
    re_path('categories/$', CategoryListAPIView.as_view(), name='categories-api-list'),
    re_path('categories/(?P<id>[0-9]+)/$', CategoryDetailAPIView.as_view(), name='categories-api-detail'),
    re_path('categories/filter/names/$', CategoriesByNameListAPIView.as_view(),
            name='categories-filter-name-api-list'),
    re_path('product-variations/$', ProductVariationCreateAPIView.as_view(), name='product-variation-api-create'),
    re_path('cart/(?P<token>[0-9A-Za-z_\-]+)/$', CartDetailAPIView.as_view(), name='cart-api-detail'),
    re_path('product-variations/(?P<id>[0-9]+)/$', ProductVariationRetrieveUpdateDeleteAPIView.as_view(),
            name='product-variations-api-detail-update-delete'),
    re_path('orders/$', OrderCreateAPIView.as_view(), name='orders-create')
]

store_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes

import json
from datetime import datetime
from random import randint
import decimal

from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import *
from rest_framework.views import APIView
from rest_framework.pagination import PageNumberPagination

from .models import *
from .serializers import *

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

# =====================================================
#   PRODUCTS
# =====================================================


class ProductsPagination(PageNumberPagination):
    page_size = 16
    page_size_query_param = 'page_size'


class ClothingProductListAPIView(ListAPIView):
    authentication_classes = []
    serializer_class = ClothingProductSimpleSerializer
    model = ClothingProduct
    queryset = ClothingProduct.objects.all()
    pagination_class = ProductsPagination

    def get_serializer_context(self):
        context = super(ClothingProductListAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context


class ClothingProductDetailAPIView(RetrieveAPIView):
    authentication_classes = []
    serializer_class = ClothingProductSimpleSerializer
    model = ClothingProduct
    lookup_field = 'id'
    queryset = ClothingProduct.objects.all()
    pagination_class = None

    def get_serializer_context(self):
        context = super(ClothingProductDetailAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context


# =====================================================
#   COLLECTIONS
# =====================================================


class ClothingCollectionListAPIView(ListAPIView):
    authentication_classes = []
    serializer_class = ClothingCollectionSerializer
    model = ClothingCollection
    queryset = ClothingCollection.objects.all()
    pagination_class = None

    def get_serializer_context(self):
        context = super(ClothingCollectionListAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context


class ClothingCollectionsByNameYearListAPIView(ListAPIView):
    authentication_classes = []
    serializer_class = ClothingCollectionSerializer
    model = ClothingCollection
    pagination_class = None

    def get_queryset(self):
        name = list(self.request.data['name'])
        year = self.request.data['year']
        queryset = ClothingCollection.objects.filter(title__in=name, year=year)
        return queryset

    def get_serializer_context(self):
        context = super(ClothingCollectionsByNameYearListAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context

    def post(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class ClothingCollectionDetailAPIView(RetrieveAPIView):
    authentication_classes = []
    serializer_class = ClothingCollectionSerializer
    model = ClothingCollection
    lookup_field = 'id'
    queryset = ClothingCollection.objects.all()
    pagination_class = None

    def get_serializer_context(self):
        context = super(ClothingCollectionDetailAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context


# =====================================================
#   CATEGORIES
# =====================================================


class CategoryListAPIView(ListAPIView):
    authentication_classes = []
    serializer_class = CategorySerializer
    model = Category
    queryset = Category.objects.all()
    pagination_class = None

    def get_serializer_context(self):
        context = super(CategoryListAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context


class CategoryDetailAPIView(RetrieveAPIView):
    authentication_classes = []
    serializer_class = CategorySerializer
    model = Category
    lookup_field = 'id'
    queryset = Category.objects.all()
    pagination_class = None

    def get_serializer_context(self):
        context = super(CategoryDetailAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context


class CategoriesByNameListAPIView(ListAPIView):
        authentication_classes = []
        serializer_class = CategorySerializer
        model = Category
        pagination_class = None

        def get_queryset(self):
            name = list(self.request.data['name'])
            queryset = Category.objects.filter(title__in=name)
            return queryset

        def get_serializer_context(self):
            context = super(CategoriesByNameListAPIView, self).get_serializer_context()
            context.update({"request": self.request})
            return context

        def post(self, request, *args, **kwargs):
            return self.list(request, *args, **kwargs)


# =====================================================
#   PRODUCT VARIATION
# =====================================================


class ProductVariationCreateAPIView(CreateAPIView):
    authentication_classes = []
    serializer_class = ProductVariationCreateSerializer
    model = ProductVariation

    def get_serializer_context(self):
        context = super(ProductVariationCreateAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=self.request.data)
        # serializer.is_valid(raise_exception=True)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        product_variation = serializer.save()

        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ipaddress = x_forwarded_for.split(',')[-1].strip()
        else:
            ipaddress = request.META.get('REMOTE_ADDR')

        try:
            token = self.request.data['cart_token']
            cart = Cart.objects.get(ip_address=ipaddress, token=token, is_active=True)
        except:
            new_token = urlsafe_base64_encode(force_bytes(randint(1,999999)))
            cart = Cart(ip_address=ipaddress, token=new_token)

        cart.save()
        product_variation.cart = cart
        product_variation.save()
        cart_serializer = CartSerializer(cart,  context={"request": request})
        return Response(cart_serializer.data, status=status.HTTP_201_CREATED)


class ProductVariationRetrieveUpdateDeleteAPIView(RetrieveUpdateDestroyAPIView):
    authentication_classes = []
    model = ProductVariation
    lookup_field = 'id'
    queryset = ProductVariation.objects.all()
    pagination_class = None

    def get_serializer_class(self):
        if self.request.method == 'PUT':
            self.serializer_class = ProductVariationCreateSerializer
        else:
            self.serializer_class = ProductVariationSerializer
        return self.serializer_class

    def get_serializer_context(self):
        context = super(ProductVariationRetrieveUpdateDeleteAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context



# =====================================================
#   CART
# =====================================================


class CartDetailAPIView(RetrieveAPIView):
    authentication_classes = []
    serializer_class = CartSerializer
    model = Cart
    lookup_field = 'token'
    queryset = Cart.objects.all()
    pagination_class = None

    def get_serializer_context(self):
        context = super(CartDetailAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context

    def get_object(self):
        token = self.kwargs.get(self.lookup_field)
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ipaddress = x_forwarded_for.split(',')[-1].strip()
        else:
            ipaddress = self.request.META.get('REMOTE_ADDR')

        try:
            cart = Cart.objects.get(ip_address=ipaddress, token=token, is_active=True)
        except:
            cart = None
        return cart


# =====================================================
#   ORDER
# =====================================================


class OrderCreateAPIView(CreateAPIView):
    authentication_classes = []
    serializer_class = OrderSerializer
    model = Order

    def get_serializer_context(self):
        context = super(OrderCreateAPIView, self).get_serializer_context()
        context.update({"request": self.request})
        return context

    def post(self, request):
        serializer = self.serializer_class(data=self.request.data)
        if not serializer.is_valid():
            return Response({'Result': 'Personal information is not valid'}, status=status.HTTP_400_BAD_REQUEST)
        shipping_address_serializer = AddressSerializer(data=request.data['shipping_address'])
        if not shipping_address_serializer.is_valid():
            return Response({'Result': 'Shipping information is not valid'}, status=status.HTTP_400_BAD_REQUEST)
        shipping_address = shipping_address_serializer.save()
        order = serializer.save(shipping_address=shipping_address, other_costs=Decimal(0.0000), shipping_cost=Decimal(0.0000))

        #Try making payment

templates/store_app/clothing_collection/clothing_collection_form.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Nueva Coleccion{% endblock %}


{% block css %}
      <link href="{% static 'css/create_obj.css' %}" rel="stylesheet">
{%  endblock %}

{% block content %}

    <div class="create-obj-div">

    <h4 class="create-obj-title">Coleccion</h4>

        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}

             <div class="row">
              <div class="form-group col-md-6 mb-0">
                {{ form.title|as_crispy_field }}
              </div>
              <div class="form-group col-md-6 mb-0">
                {{ form.year|as_crispy_field }}
              </div>
            </div>

                {{ form.description|as_crispy_field }}

                {{ form.image|as_crispy_field }}

            <div class="create-obj-button-div">
                <input class="btn btn-primary create-obj-button" type="submit" value="Guardar">
            </div>

        </form>

    </div>

{% endblock %}

templates/store_app/clothing_collection/clothing_collection_list.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Collections{% endblock %}


{% block css %}
      <link href="{% static 'css/list_obj.css' %}" rel="stylesheet">
{%  endblock %}

{% block content %}

    <div class="list-obj-title-wrapper">

        <div class="list-obj-title-nav">

            <h4 class="list-obj-title">Colecciones</h4>

            <div class="list-obj-add-div">
                <div class="list-obj-menu-div">

                    <div class="list-obj-menu-view">

                        <div class="list-obj-menu-view-icon-div">
                          <button class="btn btn-outline-light"
                          onclick="changeObjListView(false)"
                          >
                                    <span style="color: #c0a16b;">
                                       <i class="fa-solid fa-table-list"></i>
                                   </span>
                            </button>
                      </div>

                      <div class="list-obj-menu-view-icon-div">
                          <button class="btn btn-outline-light"
                            onclick="changeObjListView(true)"
                          >
                                    <span style="color: #c0a16b;">
                                       <i class="fa-solid fa-grip"></i>
                                   </span>
                            </button>
                      </div>

                    </div>

                    <button class="btn btn-outline-primary list-obj-add-button" >
                       <a href="{% url 'admin_app:collection-create' %}" class="list-obj-link">
                            <span style="color: white;">
                               <i class="fa-solid fa-plus list-obj-add"></i> Nuevo
                           </span>
                       </a>
                    </button>
                </div>
            </div>

        </div>

    </div>


{% if object_list %}
    <div class="list-obj-wrapper">

        <table class="table" id="clothingcollectionsTable">
         <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
            <th scope="col">Año</th>
            <th scope="col">Productos</th>
            <th scope="col">Detalles</th>
            <th scope="col">Eliminar</th>
        </tr>
      </thead>
            {% for collection_obj in object_list %}
                <tbody>
                    <tr>
                        <th scope="row">{{ collection_obj.id }}</th>
                         <td>{{ collection_obj.title }}</td>
                        <td>{{ collection_obj.year }}</td>
                        <td><a href="{% url 'admin_app:clothing-products-collection-filter' collection_obj.id %}" class="list-obj-link">
                            <span style="color: #c0a16b;">
                               <i class="fa-solid fa-shirt"></i> Productos
                           </span>
                        </a></td>
                        <td><a href="{% url 'admin_app:collection-update' collection_obj.id %}" class="list-obj-link">
                            <span style="color: #c0a16b;">
                               <i class="fa-solid fa-pen-to-square"></i> Editar
                           </span>
                        </a></td>
                         <td><a href="{% url 'admin_app:collection-delete' collection_obj.id %}" class="list-obj-link">
                            <span style="color: #c0a16b;">
                               <i class="fa-solid fa-trash"></i> Eliminar
                           </span>
                        </a></td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>

        <div class="grid" id="clothingcollectionGrid">
            <div class="container">
              <div class="row">
                  {% for collection_obj in object_list %}
                      <div class="col-3">
                        <a href="{% url 'admin_app:clothing-products-collection-filter' collection_obj.id %}" class="list-obj-link">

                          <div class="card collection-card">
                              <img src="{{collection_obj.image.url}}" alt="Collection {{ collection.title }}"
                                    class="card-img collection-card-image"
                                  />
                              <div class="card-body collection-card-body">
                                  {{ collection_obj.title }} {{ collection_obj.year }}
                                  <a href="{% url 'admin_app:collection-update' collection_obj.id %}" class="list-obj-link">
                                      <span style="color: #c0a16b;">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                      </span>
                                  </a>
                              </div>
                          </div>

                      </a>
                      </div>
                  {% endfor %}
            </div>
        </div>

    </div>


    <div class="list-obj-pagination-wrapper">

        {% if is_paginated %}

            <div class="container-wrap">
                    <div class="row">
                        <div class="col-md-12 col-md-offset-3 text-center">
                          <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                  <a class="page-link" href="?page={{page_obj.previous_page_number}}"
                                    >&laquo;</a
                                  >
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                  <a class="page-link" href="#">&laquo;</a>
                                </li>
                            {% endif %}

                              {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                                {% else %}
                                    <li class="page-item">
                                      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% endif %}
                              {% endfor %}

                              {% if page_obj.has_next %}
                                <li class="page-item">
                                  <a href="?page={{page_obj.next_page_number}}" class="page-link"
                                    >&raquo;</a
                                  >
                                </li>
                                {% else %}
                                    <li class="page-item disabled">
                                      <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>

                        </div>
                    </div>
            </div>
        {% endif %}

    </div>

{% else %}

    <p>No hay ninugna coleccion todavia</p>
{% endif %}

{% block script_js %}
    <script>

        var show_obj_view = function (elem) {
        elem.style.visibility = "visible";
        };

        var hide_obj_view = function (elem) {
            elem.style.visibility = "hidden";
        };

        hide_obj_view(document.getElementById('clothingcollectionsTable'))

        function changeObjListView(type_of_view){
            if(type_of_view){
                hide_obj_view(document.getElementById('clothingcollectionsTable'))
                show_obj_view(document.getElementById('clothingcollectionGrid'))
            }
            else{
                show_obj_view(document.getElementById('clothingcollectionsTable'))
                hide_obj_view(document.getElementById('clothingcollectionGrid'))
            }
        }
    </script>
{% endblock %}

{% endblock %}