admin_app/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.views.generic.base import TemplateView
from .views import *

app_name = 'admin_app'

urlpatterns = [
    re_path(r'^accounts/', include("django.contrib.auth.urls")),
    re_path(r'^$',  ClothingProductList.as_view(), name='index'),
    # Collections
    re_path(r'^collections/create/$', ClothingCollectionCreate.as_view(), name='collection-create'),
    re_path('collections/$', ClothingCollectionList.as_view(), name='collection-list'),
    re_path('collections/(?P<pk>[^/]*)/delete/$', ClothingCollectionDelete.as_view(), name='collection-delete'),
    re_path(r'^collections/(?P<pk>[^/]*)/update/$', ClothingCollectionUpdate.as_view(), name='collection-update'),
    # Categories
    re_path(r'^categories/create/$', CategoryCreate.as_view(), name='category-create'),
    re_path('categories/$', CategoryList.as_view(), name='category-list'),
    re_path('categories/(?P<pk>[^/]*)/delete/$', CategoryDelete.as_view(), name='category-delete'),
    re_path(r'^categories/(?P<pk>[^/]*)/update/$', CategoryUpdate.as_view(), name='category-update'),
    # Global Config
    re_path(r'^global-configs/create/$', GlobalConfigCreate.as_view(), name='global-config-create'),
    re_path('global-configs/$', GlobalConfigList.as_view(), name='global-config-list'),
    re_path(r'^global-configs/(?P<pk>[^/]*)/update/$', GlobalConfigUpdate.as_view(), name='global-config-update'),
    re_path(r'^global-configs/(?P<pk>[^/]*)/delete/$', GlobalConfigDelete.as_view(), name='global-config-delete'),
    # Custom Color
    re_path(r'^custom-colors/create/$', CustomColorCreate.as_view(), name='custom-color-create'),
    re_path('custom-colors/$', CustomColorList.as_view(), name='custom-color-list'),
    re_path(r'^custom-colors/(?P<pk>[^/]*)/update/$', CustomColorUpdate.as_view(), name='custom-color-update'),
    re_path(r'^custom-colors/(?P<pk>[^/]*)/delete/$', CustomColorDelete.as_view(), name='custom-color-delete'),
    # Clothing Product
    re_path(r'^clothing-products/create/$', ClothingProductCreate.as_view(), name='clothing-product-create'),
    re_path('clothing-products/$', ClothingProductList.as_view(), name='clothing-product-list'),
    re_path(r'^clothing-products/(?P<pk>[^/]*)/update/$', ClothingProductUpdate.as_view(),
            name='clothing-product-update'),
    re_path(r'^clothing-products/(?P<pk>[^/]*)/delete/$', ClothingProductDelete.as_view(),
            name='clothing-product-delete'),
    re_path(r'^collections/(?P<pk>[^/]*)/clothing-products/$', ClothingProductFilterCollection.as_view(),
            name='clothing-products-collection-filter'),
    re_path(r'^categories/(?P<pk>[^/]*)/clothing-products/$', ClothingProductFilterCategory.as_view(),
            name='clothing-products-category-filter'),
    # Orders
    re_path('orders/$', OrderList.as_view(), name='order-list'),
    re_path(r'^orders/create/$', OrderCreate.as_view(), name='order-create'),
    re_path(r'^orders/(?P<pk>[^/]*)/update/$', OrderUpdate.as_view(), name='order-update'),
    re_path(r'^orders/(?P<pk>[^/]*)/delete/$', OrderDelete.as_view(), name='order-delete'),
    re_path(r'^orders/(?P<pk>[^/]*)/datail/$', OrderDetail.as_view(), name='order-detail'),
    #Payment
    re_path(r'^payments/create/$', PaymentCreate.as_view(), name='payment-create'),
    re_path('payments/$', PaymentList.as_view(), name='payment-list'),
    re_path('categpaymentsories/(?P<pk>[^/]*)/delete/$', PaymentDelete.as_view(), name='payment-delete'),
    re_path(r'^payments/(?P<pk>[^/]*)/update/$', PaymentUpdate.as_view(), name='payment-update'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gwendolyn:wght@400;700&family=Montserrat:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;1,100;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

 <link href="{% static 'css/custom_base.css' %}" rel="stylesheet" type="text/css">

{% block css %}

{%  endblock %}


    <title>{% block title %}Habaneras de Lino | Admin{% endblock %}</title>
</head>
<body class="body">
  <main>

  {% if user.is_authenticated %}

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="{% url 'admin_app:index' %}">Habaneras de Lino</a>
            <ul class="navbar-nav mt-2 mt-lg-0 justify-content-center">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin_app:clothing-product-list' %}">Productos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:collection-list' %}">Colecciones</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:category-list' %}">Categorias</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:custom-color-list' %}">Colores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:order-list' %}">Ordenes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:payment-list' %}">Pagos</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:global-config-list' %}">Configuracion</a>
              </li>
                 <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_app:logout' %}">Log Out</a>
              </li>
            </ul>
          </div>
        </nav>

        {% block content %}
        
        {% endblock %}

  {% else %}

       <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Habaneras de Lino</a>
      </div>
    </nav>

    <p>You are not logged in</p>
    <a href="{% url 'admin_app:login' %}">Log In</a>

{% endif %}

  </main>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block script_js %}

    {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Habaneras de Lino | Admin{% endblock %}


{% block content %}
  {% if user.is_authenticated %}
      <div>
      </div>
    {% else %}

      <p>You are not logged in</p>
      <a href="{% url 'admin_app:login' %}">Log In</a>


  {% endif %}
{% endblock %}